version: '3'
services:

  dh_proxy:
    ports:
      - "1883:1883"
    links:
      - mqtt_broker1
      - mqtt_broker2
    volumes:
      - "./nginx-mqtt-brokers.conf:/etc/nginx/stream.d/nginx-mqtt-brokers.conf:ro,Z"

  mqtt_broker1:
    image: devicehive/devicehive-mqtt:development
    environment:
      - WS_SERVER_URL=ws://playground-dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false

  mqtt_broker2:
    image: devicehive/devicehive-mqtt:development
    environment:
      - WS_SERVER_URL=ws://playground-dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false

  redis:
    image: redis:alpine
